import type { Metadata } from 'next';
import { Geist, Geist_Mono } from 'next/font/google';
import Script from 'next/script';
import Header from '@/components/Header';
import { cookies } from 'next/headers';

import './globals.css';

const geistSans = Geist({
    variable: '--font-geist-sans',
    subsets: ['latin'],
});

const geistMono = Geist_Mono({
    variable: '--font-geist-mono',
    subsets: ['latin'],
});

export const metadata: Metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
};

export default async function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    const loggedIn = (await cookies()).get('loggedIn')?.value;

    return (
        <html lang="en">
            <head>
                {/* Im adding this script to be executed before the first paint and to avoid any FOUC - Flash of unstyled content*/}
                <Script id="set-dark-mode" strategy="beforeInteractive">
                    {`
                        if (window.matchMedia('(prefers-color-scheme: dark)').matches) {
                        document.documentElement.classList.add('dark');
                        }
                        window.matchMedia('(prefers-color-scheme: dark)').addEventListener('change', e => {
                        if (e.matches) {
                            document.documentElement.classList.add('dark');
                        } else {
                            document.documentElement.classList.remove('dark');
                        }
                        });
                    `}
                </Script>
            </head>
            <body
                className={`${geistSans.variable} ${geistMono.variable} antialiased h-screen flex flex-col`}
            >
                <Header initialLoggedIn={loggedIn} />
                {children}
            </body>
        </html>
    );
}
